name: client
description: Graduation Project for BSTU 2023.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.3.3
  http: ^1.1.0
  lottie: ^2.6.0
  logger: ^2.0.2+1
  shimmer: ^3.0.0
  equatable: ^2.0.5
  animations: ^2.0.8
  flutter_svg: ^2.0.7
  flutter_bloc: ^8.1.3
  google_sign_in: ^6.1.4
  cupertino_icons: ^1.0.5
  email_validator: ^2.1.17
  shared_preferences: ^2.2.1
  sign_in_with_apple: ^5.0.0
  permission_handler: ^11.0.0
  elegant_notification: ^1.11.0
  flutter_native_splash: ^2.3.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  remove_alpha_ios: true
#  image_path: "assets/icons/favicon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/

  fonts:
    # 1. Poppins font
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
