name: graduation_ap
description: "Admin panel for Graduation project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.3.3
  intl: ^0.19.0
  logger: ^2.0.2+1
  equatable: ^2.0.5
  geolocator: ^11.0.0
  flutter_bloc: ^8.1.3
  firebase_core: ^2.30.1
  cupertino_icons: ^1.0.6
  # image_picker_web: ^3.1.1
  firebase_storage: ^11.7.4
  flutter_icon_snackbar: ^1.1.4
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    # 1. Poppins font
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
    # 2. Poiret font
    - family: Poiret
      fonts:
        - asset: assets/fonts/poiret/PoiretOne-Regular.ttf
          weight: 400
    # 3. OpenSans font
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/open_sans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/open_sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans-ExtraBold.ttf
          weight: 800