// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxEUq-enOQ9t3-vI2zFi478rlbecHv848',
    appId: '1:768074138212:web:2f7f258a43df90c09c9571',
    messagingSenderId: '768074138212',
    projectId: 'pizzas-811dc',
    authDomain: 'pizzas-811dc.firebaseapp.com',
    storageBucket: 'pizzas-811dc.appspot.com',
    measurementId: 'G-X2GV83Z0BJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOOFOGSFsOfx-hqHX2GRwUr_E1pqg8BMk',
    appId: '1:768074138212:android:90444f2b843129d59c9571',
    messagingSenderId: '768074138212',
    projectId: 'pizzas-811dc',
    storageBucket: 'pizzas-811dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8QlT1iqETD96UO7cWwKCA33JzzxI-ZtM',
    appId: '1:768074138212:ios:fae0254d0153de879c9571',
    messagingSenderId: '768074138212',
    projectId: 'pizzas-811dc',
    storageBucket: 'pizzas-811dc.appspot.com',
    iosBundleId: 'com.kapold.graduationAp',
  );
}
